dist_fastmod <- read.table("~/dev/studienarbeit-wot/results/fastmod/community_size_dist.dat")
dist_copra <- read.table("~/dev/studienarbeit-wot/results/copra/community_size_dist.dat")
dist_label <- read.table("~/dev/studienarbeit-wot/results/label-prop/community_size_dist.dat")
dist_bl2 <- read.table("~/dev/studienarbeit-wot/results/blondel-l2/community_size_dist.dat")
dist_bl5 <- read.table("~/dev/studienarbeit-wot/results/blondel-l5/community_size_dist.dat")
xl <- c(3,max(range(dist_fastmod), range(dist_copra), range(dist_label), range(dist_bl2), range(dist_bl5)))
yl <- c(1,max(range(dist_fastmod[2]), range(dist_copra[2]), range(dist_label[2]), range(dist_bl2[2]), range(dist_bl5[2])))
plot(dist_copra, log="xy", col="blue", xlab="Grösse", ylab="Anzahl", cex=0.8, pch=2, xlim=xl, ylim=yl)
legend(x="topright", legend="COPRA", col="blue", pch=2)
quartz.save("dev/studienarbeit-wot/ausarbeitung/images/community-size-dist_copra.pdf", type="pdf")
plot(dist_fastmod, log="xy", col="blue", xlab="Grösse", ylab="Anzahl", cex=0.8, pch=2, xlim=xl, ylim=yl)
legend(x="topright", legend="FM", col="blue", pch=2)
quartz.save("dev/studienarbeit-wot/ausarbeitung/images/community-size-dist_fastmod.pdf", type="pdf")
plot(dist_label, log="xy", col="blue", xlab="Grösse", ylab="Anzahl", cex=0.8, pch=2, xlim=xl, ylim=yl)
legend(x="topright", legend="LP", col="blue", pch=2)
quartz.save("dev/studienarbeit-wot/ausarbeitung/images/community-size-dist_label.pdf", type="pdf")
plot(dist_bl2, log="xy", col="blue", xlab="Grösse", ylab="Anzahl", cex=0.8, pch=2, xlim=xl, ylim=yl)
legend(x="topright", legend="BL l=2", col="blue", pch=2)
quartz.save("dev/studienarbeit-wot/ausarbeitung/images/community-size-dist_bl2.pdf", type="pdf")
plot(dist_bl5, log="xy", col="blue", xlab="Grösse", ylab="Anzahl", cex=0.8, pch=2, xlim=xl, ylim=yl)
legend(x="topright", legend="BL l=5", col="blue", pch=2)
quartz.save("dev/studienarbeit-wot/ausarbeitung/images/community-size-dist_bl5.pdf", type="pdf")
