dist_fastmod <- read.table("~/dev/studienarbeit-wot/results/fastmod/community_size_dist.dat")
dist_copra <- read.table("~/dev/studienarbeit-wot/results/copra/community_size_dist.dat")
dist_label <- read.table("~/dev/studienarbeit-wot/results/label-prop/community_size_dist.dat")
dist_cmod500 <- read.table("~/dev/studienarbeit-wot/results/cliquemod-500/community_size_dist.dat")
plot(dist_copra, log="xy", col="blue", main="Grössenverteilung der Communities", xlab="Grösse", ylab="Anzahl", cex=0.8, pch=2)
points(dist_fastmod, col="red", pch=0)
points(dist_label, col="green", pch=1)
points(dist_cmod500, col="violet", pch=3)
legend(x="topright", legend=c("FM", "LP", "COPRA", "CM-500"), col=c("red", "green", "blue", "violet"), pch=c(0,1,2,3))
quartz.save("dev/studienarbeit-wot/ausarbeitung/community-size-dist.pdf", type="pdf")
