n2 <- scan("dev/studienarbeit-wot/results/basic-properties/scc-44952_n2.values")
n3 <- scan("dev/studienarbeit-wot/results/basic-properties/scc-44952_n3.values")
n4 <- scan("dev/studienarbeit-wot/results/basic-properties/scc-44952_n4.values")
n5 <- scan("dev/studienarbeit-wot/results/basic-properties/scc-44952_n5.values")
par(lab=c(6,8,7))
plot(ecdf(n5), xlim=c(0,max(n5)), lty=5, xlab="number of nodes in h-neighbourhood", main="")
lines(ecdf(n4), lty=2)
lines(ecdf(n3), lty=3)
lines(ecdf(n2), lty=4)
abline(h=0.75)
abline(h=0.5)
legend(locator(1), "h=2", bty="n")
legend(locator(1), "h=3", bty="n")
legend(locator(1), "h=4", bty="n")
legend(locator(1), "h=5", bty="n")
quartz.save("/Users/ulricha/dev/studienarbeit-wot/ausarbeitung/images/neighbourhood-cdf.pdf", type="pdf")