n2 <- scan("dev/studienarbeit-wot/results/basic-properties/scc-44952_n2.values")
n3 <- scan("dev/studienarbeit-wot/results/basic-properties/scc-44952_n3.values")
n4 <- scan("dev/studienarbeit-wot/results/basic-properties/scc-44952_n4.values")
n5 <- scan("dev/studienarbeit-wot/results/basic-properties/scc-44952_n5.values")
par(lab=c(6,8,7))
plot(ecdf(n5), xlim=c(0,max(n5)), lty=5, col="red", xlab="Anzahl Knoten in Nachbarschaft", main="")
lines(ecdf(n4), lty=2, col="green")
lines(ecdf(n3), lty=3, col="blue")
lines(ecdf(n2), lty=4, col="brown")
abline(h=0.8)
abline(h=0.5)
legend(locator(1), "n=2", bty="n")
legend(locator(1), "n=3", bty="n")
legend(locator(1), "n=4", bty="n")
legend(locator(1), "n=5", bty="n")
quartz.save("/Users/ulricha/dev/studienarbeit-wot/ausarbeitung/images/neighbourhood-cdf.pdf", type="pdf")