mscc <- read.table("dev/studienarbeit-wot/results/time/mscc-size.dat")
whole <- read.table("dev/studienarbeit-wot/results/time/whole_graph-key_creation_cumulative_stats")
# yl <- c(1,max(whole))
mscc_ts <- ts(mscc[2], start=c(1992, 5), frequency=12)
whole_ts <- ts(whole[2], start=c(1992,5), frequency=12)
par(lab=c(8,8,7))
plot(mscc_ts, xlab="time", ylab="number of keys")
quartz.save("/Users/ulricha/dev/studienarbeit-wot/ausarbeitung/images/mscc-size-time.pdf")
plot(whole_ts, xlab="time", ylab="number of keys")
quartz.save("/Users/ulricha/dev/studienarbeit-wot/ausarbeitung/images/whole-size-time.pdf")